spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
  address: "0.0.0.0"